version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4300:4300"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27000:27017"
